################################################################################
#   CONFIGURATIONS FOR FITTING FaIRGP
################################################################################

# DATASET
dataset:
  # Path to data directory
  dirpath: data/

  # Keys of scenarios to load for training (commment scenarios to remove them from training set)
  keys:
    - historical
    - ssp126
    - ssp245
    - ssp370
    - ssp585


# TRAINING
training:
  # Number of training epochs
  n_epochs: 60

  # Learning rate
  lr: 0.1
