################################################################################
#   CONFIGURATIONS FOR FITTING GFAIR PROCESS
################################################################################

# DATASET
dataset:
  # Path to data directory
  dirpath: data/

  # Keys of scenearios to load
  keys:
    - historical
    - ssp126
    - ssp245
    - ssp370
    - ssp585



# MODEL SPECIFICATIONS
model:



# TRAINING
training:
  # Number of training epochs
  n_epochs: 100
  # n_epochs: 2

  # Learning rate
  lr: 0.1



# EVALUATION
evaluation:
