################################################################################
#   CONFIGURATIONS FOR FITTING GFAIR PROCESS
################################################################################

# DATASET
dataset:
  # Path to data directory
  dirpath: data/

  # Keys of scenearios to load
  keys:
    - historical
    # - ssp126
    # - ssp245
    # - ssp370
    # - ssp585



# MODEL SPECIFICATIONS
model:
  # Specification of inducing scenario
  inducing_scenario:
    # Name of inducing scenario
    key: historical

    # Number of inducing times
    n_inducing_times: 10

    # Number of inducing lats
    n_inducing_lats: 10

    # Number of inducing lons
    n_inducing_lons: 10



# TRAINING
training:
  # Number of training epochs
  n_epochs: 16

  # Learning rate
  lr: 0.01

  # Number of time steps in a batch
  batch_size_time: 16

  # Number of latitudes in a batch
  batch_size_lat: 8

  # Number of longitudes in a batch
  batch_size_lon: 8



# EVALUATION
evaluation:
